#!/usr/bin/env python
import json
import logging
import os
import subprocess
import sys

# DATABASE_ENDPOINT = sys.argv[1]

logging.basicConfig(
    level=logging.INFO,
    stream=sys.stdout,
    format='%(levelname)s: %(message)s',
)

def build_vcap_services():
    logging.debug("Executing build_vcap_services...")

    vcap_services_data = open("vcap_services.json").read()

    logging.debug("Set environment variable VCAP_SERVICES: \n {0}".format(vcap_services_data))
    result = json.dumps(vcap_services_data)
    return result

if __name__ == '__main__':

    #if os.getenv('DATABASE_ENDPOINT') is None:
    #    logging.error(
    #        'VCAP_SERVICES environment variable not found.'
    #    )

    vcap_services = build_vcap_services().replace("\\n", "")
    vcap_services = vcap_services.replace("\"", "\\\"")
    sys.stdout.write(vcap_services)
    sys.stdout.flush()
    sys.exit(0)
