#!/usr/bin/env python3
import json
import logging
import os
import subprocess
import sys
import shutil

from buildpack import java, runtime, util
from buildpack.stage import DOT_LOCAL_LOCATION

BUILD_PATH = sys.argv[1]
CACHE_PATH = sys.argv[2]

logging.basicConfig(
    level=logging.INFO,
    stream=sys.stdout,
    format='%(levelname)s: %(message)s',
)

def export_vcap_services():
    logging.debug("Executing build_vcap_services...")

    vcap_services = dict()
    vcap_services['PostgreSQL'] = [{'credentials': { 'uri': "postgres://mendix:mendix@172.17.0.2:5432/mendix" } }]

    vcap_services_str = json.dumps(vcap_services , sort_keys=True, indent=4,
        separators=(',', ': '))
    logging.debug("Set environment variable VCAP_SERVICES: \n{0}"
        .format(vcap_services_str))

    os.environ['VCAP_SERVICES'] = vcap_services_str
    os.environ["PATH"] += os.pathsep + "/opt/mendix/buildpack"

def call_buildpack_compilation():
    logging.debug("Executing call_buildpack_compilation...")
    return subprocess.check_call(["/opt/mendix/buildpack/buildpack/stage.py", BUILD_PATH, CACHE_PATH])

def remove_jdk():
    logging.info("Removing JDK...")
    runtime.get_version(BUILD_PATH)
    
    jdk = java.determine_jdk(runtime.get_java_version(runtime.get_version(BUILD_PATH)), 'jdk')
    jdk_path = os.path.join(DOT_LOCAL_LOCATION, java.compose_jvm_target_dir(jdk))
    if os.path.exists(jdk_path):
        shutil.rmtree(jdk_path, ignore_errors=False)

def fix_logfilter():
    exclude_logfilter = os.getenv("EXCLUDE_LOGFILTER", "true").lower() == "true"
    if exclude_logfilter:
        logging.info("Removing mendix-logfilter executable")
        shutil.rmtree("/opt/mendix/build/.local/mendix-logfilter")
        shutil.rmtree("/opt/mendix/buildpack/vendor/mendix-logfilter")
    else:
        os.chmod("/opt/mendix/build/.local/mendix-logfilter/mendix-logfilter", 0o0755)

def make_dependencies_reusable():
    logging.info("Making dependencies reusable...")
    shutil.move("/opt/mendix/build/runtimes", "/var/mendix/build/")
    shutil.move("/opt/mendix/build/.local/usr", "/var/mendix/build/.local/")
    # separate cacerts from reusable jre components
    jre = java.determine_jdk(runtime.get_java_version(runtime.get_version(BUILD_PATH)), 'jre')
    jvm_location_reusable = os.path.join("/var/mendix/build/.local/", java.compose_jvm_target_dir(jre))
    jvm_location_customized = os.path.join(DOT_LOCAL_LOCATION, java.compose_jvm_target_dir(jre))
    cacerts_file_source = os.path.join(jvm_location_reusable, "lib", "security", "cacerts")
    cacerts_file_target = os.path.join(jvm_location_customized, "lib", "security", "cacerts")
    util.mkdir_p(os.path.dirname(cacerts_file_target))
    os.rename(cacerts_file_source, cacerts_file_target)

if __name__ == '__main__':
    logging.info("Mendix project compilation phase...")

    export_vcap_services()
    exit_code = call_buildpack_compilation()
    if exit_code != 0:
        sys.exit(exit_code)
    remove_jdk()
    fix_logfilter()
    make_dependencies_reusable()

