#!/usr/bin/env python
import json
import logging
import os
import subprocess
import sys

logging.basicConfig(
    level=logging.INFO,
    stream=sys.stdout,
    format='%(levelname)s: %(message)s',
)

def export_vcap_variables():
    logging.debug("Executing build_vcap_variables...")

    vcap_services_data = open("vcap_services.json").read()
    logging.info("Set environment variable VCAP_SERVICES: \n {0}".format(vcap_services_data))
    os.environ['VCAP_SERVICES'] = vcap_services_data

    vcap_application_data = open("vcap_application.json").read()
    logging.info("Set environment variable VCAP_APPLICATION: \n {0}".format(vcap_application_data))
    os.environ['VCAP_APPLICATION'] = vcap_application_data

def call_builpack_startup():
    logging.debug("Executing call_builpack_startup...")
    subprocess.call(["python", "/build/start.py"])


if __name__ == '__main__':
    export_vcap_variables()
    call_builpack_startup()
    sys.exit(0)
